name: ModIsom
version: 2.3.3
date: 2016-01-08
description: |
    Computing automorphisms and checking isomorphisms for modular group algebras of finite p-groups

authors:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

maintainers:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Alexander Konovalov
      url: http://blogs.cs.st-andrews.ac.uk/alexk/

GAP: ">=4.7"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"

www: http://www.icm.tu-bs.de/~beick/soft/modisom/
readme: README
packageinfo: http://www.icm.tu-bs.de/~beick/soft/modisom/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/~beick/soft/modisom/modisom-2.3.3.tar.gz

abstract: |
    The <span class="pkgname">ModIsom</span> package contains various methods for computing with nilpotent associative algebras. In particular, it contains a method to determine the automorphism group and to test isomorphis of such algebras over finite fields and of modular group algebras of finite p-groups, and it contains a nilpotent quotient algorithm for finitely presented associative algebras and a method to determine Kurosh algebras.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
